services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: php:8.2-apache
    volumes:
      - ./src:/var/www/html
    ports:
      - "8080:80" # Map host port 8080 to container port 80
    environment:
      - GIT_REPO=https://github.com/OscarHenrichs/api_ranking
      - GIT_BRANCH=main
      - DB_HOST=db
      - DB_USER=developer
      - DB_PASSWORD=1234@Abc
      - DB_NAME=api_ranking
      - DB_PORT=3306

    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234@root
      MYSQL_DATABASE: api_ranking
      MYSQL_USER: developer
      MYSQL_PASSWORD: 1234@Abc
    ports:
      - "3306:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10

volumes:
  mysql_data:
